name: QA

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Output Bikeshed to HTML
        uses: netwerk-digitaal-erfgoed/bikeshed-action@v1
